# Installation of AWX Server

- name: Create directory for awx source
  file:
    path: "{{ awxSourceCodePath }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true

- name: Create directory for postgres data
  file:
    path: "{{ postgres_data_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true

- name: Create directory for docker_compose_dir
  file:
    path: "{{ docker_compose_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true

- name: Create directory for awx projets
  file:
    path: "{{ project_data_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true


- name: Check AWX code is not already there
  stat:
    path: "{{ awxSourceCodePath }}/installer"
  register: awxSourceCodePathRegister

- name: Checkout AWX docker compose files
  git:
    repo: https://github.com/ansible/awx.git
    dest: "{{ awxSourceCodePath }}"
    version: 15.0.1
    clone: yes
    update: no
  when: not awxSourceCodePathRegister.stat.exists

- name: Generate the setup for containers
  template:
    src: customAwxInventory
    dest: "{{ awxSourceCodePath }}/installer/customAwxInventory"
    mode: 0644

- name: Execute the ansible playbook 
  command: ansible-playbook -i customAwxInventory install.yml
  args:
    chdir: "{{ awxSourceCodePath }}/installer"
