---
# tasks file for yumDependencies
# We use YUM here and not APT because it will be executed in the virtualenv Python in the docker container which uses YUM

# Add repo
# - name: Add repository
#   yum_repository:
#     name: ansible-tower-cli-el7
#     description: Ansible tower cli YUM repo
#     baseurl: https://releases.ansible.com/ansible-tower/cli/

# - name: Install dependencies 
#   yum:
#     name:
#       - ansible-tower-cli
#     state: latest
#     #update_cache: true
#   become: true

- name: Install awxkit with pip
  command: pip install awxkit