# The playbook provides information it asked to the user
# * awx_username
# * awx_password
# * keepassxc_password
# This role checks password confirmation

# Then it generates automatically some secrets
# * secret_key 
# * pg_password

# Then generate SSH key pair with passphrase for admin and one for guests: TODO

# It finally store all secrets in a keypass file (TODO: Add the 2 passphrases)

- name: Install dependencies  
  apt:
    pkg:
      - keepassxc
    state: latest
    update_cache: true
  become: true

- name: Check awx_password and awx_password_confirm match
  debug: msg="Les mots de passe AWX ne correspondent pas"
  when: awx_password != awx_password_confirm
  failed_when: awx_password != awx_password_confirm

- name: Check keepassxc_password and keepassxc_password_confirm match
  debug: msg="Les mots de passe ne correspondent pas"
  when: keepassxc_password != keepassxc_password_confirm
  failed_when: keepassxc_password != keepassxc_password_confirm

- name: Generation of credentials (pg_password and awx_secret_key)
  set_fact:
    awx_secret_key: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits,punctuation') }}"
    pg_password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits,punctuation') }}"

- name: Create a keepass container
  expect:
    command: keepassxc-cli db-create {{ keepassFile }} -p
    responses:
      '(.*)Enter password to encrypt database(.*)': {{ keepassxc_password}}
      '(.*)Repeat password(.*)': {{ keepassxc_password}}
  no_log: true

- name: Add awx password in the keepass container
  expect:
    command: "keepassxc-cli add -u {{ awx_username }} -p --url "http://localhost" {{ keepassFile }} awx"
    responses:
      '(.*)Enter password to unlock(.*)': {{ keepassxc_password}}
      '(.*)Enter password for new entry(.*)': {{ awx_password }}
  no_log: true

- name: Add PG password in the keepass container
  expect:
    command: "keepassxc-cli add -u {{ pg_username }} -p {{ keepassFile }} pg"
    responses:
      '(.*)Enter password to unlock(.*)': {{ keepassxc_password}}
      '(.*)Enter password for new entry(.*)': {{ pg_password }}
  no_log: true

- name: Add AWX secret in the keepass container
  expect:
    command: "keepassxc-cli add -p {{ keepassFile }} AWX_secret"
    responses:
      '(.*)Enter password to unlock(.*)': {{ keepassxc_password}}
      '(.*)Enter password for new entry(.*)': {{ awx_secret_key }}
  no_log: true


