# Retrieve credential information if we play the playbook several times

- name: KeepassXC password
  pause:
    prompt: "Entrez le nom d'utilisateur pour le fichier keepass. Nous allons l'utiliser pour vous afficher les mots de passe à rentrer pour poursuivre votre installation."
    echo: no
  register: keepassxc_password_input

- name: Set KeepassXC password
  set_fact:
    keepassxc_password: "{{ keepassxc_password_input.user_input }}"

- name: Display AWX info
  command: "keepassxc-cli show -q -s {{ keepassFilePath }}/{{ keepassFile }} awx"
  args:
    stdin: "{{ keepassxc_password }}"
  register: out
- debug: msg="{{out.stdout_lines}}"
  
- name: AWX username
  pause:
    prompt: "Entrez le nom d'utilisateur pour le serveur awx"
  register: awx_username_input
  
- name: AWX password
  pause:
    prompt: "Entrez le mot de passe pour l'accès au server awx"
  register: awx_password_input

- name: Display PG info
  command: "keepassxc-cli show -q -s {{ keepassFilePath }}/{{ keepassFile }} pg"
  args:
    stdin: "{{ keepassxc_password }}"
  register: out
- debug: msg="{{out.stdout_lines}}"
  
- name: PG password
  pause:
    prompt: "Entrez le mot de passe pour l'accès à la base postgresql"
  register: pg_password_input

- name: Display AWX_secret info
  command: "keepassxc-cli show -q -s {{ keepassFilePath }}/{{ keepassFile }} AWX_secret"
  args:
    stdin: "{{ keepassxc_password }}"
  register: out
- debug: msg="{{out.stdout_lines}}"

- name: AWX secret
  pause:
    prompt: "Entrez la clé secréte du serveur awx"
  register: awx_secret_input

- name: Generation of credentials (pg_password and awx_secret_key)
  set_fact:
    awx_username: "{{ awx_username_input.user_input }}"
    awx_password: "{{ awx_password_input.user_input }}"
    awx_secret_key: "{{ awx_secret_input.user_input }}"
    pg_password: "{{ pg_password_input.user_input }}"
