---
# tasks file for secretStorage

- name: Check AWX code is not already there
  stat:
    path: "{{ keepassFilePath }}/{{ keepassFile }}"
  register: keepassFilePathRegister

- name: Installation of AWX server as it is not running
  include: 01_storeSecrets.yml
  when: not keepassFilePathRegister.stat.exists
