---
# tasks file for secretStorage

- name: Check AWX code is not already there
  stat:
    path: "{{ secretPath }}"
  register: secretPathRegister

- name: Installation of AWX server as it is not running
  include: 01_storeSecrets.yml
  when: not secretPathRegister.stat.exists