---
# tasks file for secretStorage

- name: Check AWX code is not already there
  stat:
    path: "{{ keepassFilePath }}/{{ keepassFile }}"
  register: keepassFilePathRegister

- name: Creation of secrets
  include: 01_storeSecrets.yml
  when: not keepassFilePathRegister.stat.exists

- name: Get secrets
  include: 02_getSecrets.yml
  when: keepassFilePathRegister.stat.exists