---
# tasks file for protectedDns
- name: Fix ansible issue with ansible (https://github.com/ansible/ansible/issues/5725)
  file:
    path: "~/.ansible"
    state: absent
  become: true

- copy:
    src: hosts
    dest: /etc/hosts
    unsafe_writes: yes # Usefull for the docker virtual guest container (https://github.com/moby/moby/issues/9295)
  become: true