---
# vars file for awxServer
awx_container_name: awx_web
awxSourceCodePath: /opt/clap/awx/source

awx_task_hostname: awx
awx_web_hostname: awxweb
postgres_data_dir: "/opt/clap/awx/pgdata"
host_port: 8081
host_port_ssl: 443
docker_compose_dir: "/opt/clap/awx/compose"
project_data_dir: "/opt/clap/awx/clap/projects"

pg_username: awx

pg_database: awx
pg_port: 5432
#pg_sslmode=require


# The following variables will be defined by the ansible role "secretStorage", so no need to setup them
# NB: it's a limitation of the "official" postgres helm chart
# pg_password: awxpass
# AWX Secret key
# It's *very* important that this stay the same between upgrades or you will lose the ability to decrypt
# your credentials
# secret_key: awxsecret
# This will create or update a default admin (superuser) account in AWX, if not provided
# then these default values are used
#admin_user: admin
#admin_password: password
