#- name: Include a play after another play
#  import_playbook: otherplays.yaml

- name: Création d'un poste invité virtuel pour les tests
  hosts: localhost
  connection: local

  tasks:
    # We use YUM here and not APT because it will be executed in the virtualenv Python in the docker container which uses YUM
    - name: Install dependencies 
      yum:
        name:
          - docker
        state: latest
        #update_cache: true
      become: true

    - name: Clone the repo
      git:
        repo: 'https://github.com/paul-p/docker-headless-vnc-container.git'
        dest: /opt/clap/VirtualGuestDockerImage/
        update: yes
        clone: yes
      become: true

    - name: Build the docker image - it could takes a long time
      command: 'docker build -t clap_virtual_guest_image .'
      args:
        chdir: '/opt/clap/VirtualGuestDockerImage/'
      become: true

    - name: Start the container
      command: "docker run -d --name clap_virtual_guest_container --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --expose 22 clap_virtual_guest_image"
      become: true

    - name: Create the user
      command: "docker exec -t clap_virtual_guest_container /dockerstartup/createUser.sh {{ GUEST_USERNAME }} {{ GUEST_PASSWORD }}"
      become: true