#- name: Include a play after another play
#  import_playbook: otherplays.yaml

- name: Test d'excution sur les postes invités
  hosts: all

  roles:
    - guestSessions
    - protectedDns
    - softwares