#- name: Include a play after another play
#  import_playbook: otherplays.yaml

- name: Installation du post Administrateur
  hosts: localhost
  connection: local

  vars:
    test : "test"

  roles:
    - awxServer
