#- name: Include a play after another play
#  import_playbook: otherplays.yaml

- name: Découverte des postes invités avec NMAP
  hosts: localhost
  connection: local

  tasks:

    # We use YUM here and not APT because it will be executed in the virtualenv Python in the docker container which uses YUM
    - name: Install dependencies 
      yum:
        name:
          - net-tools
          - nmap
        state: latest
        #update_cache: true
      become: true

    - name: Start scan
      debug: msg="Le scan NMAP va se faire sur la plage d'IP suivante {{ ip_range }}."

    - name: Scan hosts
      command: "nmap -p 22 {{ ip_range }} --open"
      register: nmap

    - name: Test
      debug: msg="{{ nmap.stdout }}"

    - set_fact:
        guest_ips: "{{ nmap.stdout | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"
      vars:
        regexp3: '(\d+\.\d+\.\d+\.\d+)'

    - name: Results
      debug: msg="Voici les postes sur votre réseau local qui ont le port SSH ouvert {{ guest_ips | string }}."