
- name: Installation du post Administrateur
  hosts: localhost
  connection: local

  vars_prompt:

    - name: keepassxc_password
      prompt: Entrez le mot de passe souhaité pour le fichier keepassXC dans lequel seront stockés les autres mots de passe

    - name: keepassxc_password
      prompt: Confirmez ce mot de passe

    - name: awx_username
      prompt: Entrez le nom d'utilisateur souhaité pour le serveur awx
      private: no

    - name: awx_password
      prompt:  Entrez le mot de passe souhaité à cet utilisateur

    - name: awx_password_confirm
      prompt:  Confirmez ce mot de pass
    
    
# - name: Test local
#   hosts: localhost
#   connection: local
#   vars_prompt:

  # - name: guest_username
  #   prompt: Entrez le nom d'utilisateur existant sur vos postes invités
  #   private: no

  # - name: guest_password
  #   prompt:  Entrez le mot de passe associé à cet utilisateur

  # - name: guest_password_confirm
  #   prompt:  Confirmez ce mot de passe
    
  tasks:
    # - name: Test container
    #   docker_container_info:
    #     name: awx_web
    #   register: result
    # - name: Check AWX server existence
    #   stat:
    #     path: "/tmp"
    #   register: check
    # - name: Test
    #   debug: msg="check result is {{result.container.State.Status}}"

    # - name: Pause to get some sensitive input
    #   pause:
    #     prompt: "Enter a secret"
    #     echo: no

    # - name: Generation of passwords
    #   set_fact:
    #     password_test: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits,punctuation') }}"

    # - name: read
    #   debug: msg="Ok {{ password_test }}"

    # - name: Execute the ansible playbook 
    #   expect:
    #     command: keepassxc-cli db-create test3 -p
    #     responses:
    #       '(.*)Enter password to encrypt database(.*)': "test"
    #       '(.*)Repeat password(.*)': "test"
    #   no_log: true



