---
# tasks file for softwares
- name: Clean repos
  command: apt update --fix-missing
  become: true

- name: Uninstall Transmission
  apt:
    name: transmission-gtk
    state: absent
  become: true

- name: Install last version of firefox 
  apt:
    pkg:
      - firefox
      - unzip
      - firefox-locale-fr
    state: latest
  become: true